stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo $DOCKER_HUB_PWD | docker login --username hashiwokakero --password-stdin
    - docker build --network host -t hashiwokakero/digit:latest .
    - docker push hashiwokakero/digit:latest

deploy:
  stage : deploy
  script:
    - docker rm -f $(docker ps -aq --filter name=digit) || true
    - docker system prune -f
    - docker run -d --name digit -p 50003:5000 hashiwokakero/digit:latest

