stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo $DOCKER_HUB_PWD | docker login --username hashiwokakero --password-stdin
    - docker build --network host -t hashiwokakero/solver:latest .
    - docker push hashiwokakero/solver:latest

deploy:
  stage : deploy
  script:
    - docker rm -f $(docker ps -aq --filter name=solver) || true
    - docker system prune -f
    - docker run -d --name solver -p 50004:5000 hashiwokakero/solver:latest
